### ISSUE TITLE
Raspberry pinout

### ISSUE THREAD

**Issue by kaisarantonn** [RobRobM/e3s1-on-klipper#1]
Do you have pinout / GPio diagrams for S1 Board? 

I want to connects raspberry pi using pinout so the pi can stay inside.

And having usb plugged outside isnt the best aesthetic.

**Comment by anmarcu** [comment]
The only schema is in user manual, you can download it from the official website.

**Comment by anmarcu** [comment]
> Do you have pinout / GPio diagrams for S1 Board?
> 
> I want to connects raspberry pi using pinout so the pi can stay inside.
> 
> And having usb plugged outside isnt the best aesthetic.

@kaisarantonn 
The only schema is in user manual, you can download it from the official website.
