### ISSUE TITLE
start_print.cfg not working with prusa slicer

### ISSUE THREAD

**Issue by Thormus** [RobRobM/e3s1-on-klipper#2]
hi,

Thank you for posting all of your configs. I am trying to use prusa slicer (super slicer not working with m1 mac), and i get this error when trying to use your start macro.

Error evaluating 'gcode_macro START_PRINT:gcode': UndefinedError: 'dict object' has no attribute 'print_count'

I was wondering what start g code settings you have in super slicer? I am trying to just use START_PRINT.

**Comment by anmarcu** [comment]
> hi,
> 
> Thank you for posting all of your configs. I am trying to use prusa slicer (super slicer not working with m1 mac), and i get this error when trying to use your start macro.
> 
> Error evaluating 'gcode_macro START_PRINT:gcode': UndefinedError: 'dict object' has no attribute 'print_count'
> 
> I was wondering what start g code settings you have in super slicer? I am trying to just use START_PRINT.

@Thormus
1. Read the descriotion from this repo (readme file)
2. You can simply comment that part, is not mandatory.

![Screenshot_20220429_014954_com android chrome](https://user-images.githubusercontent.com/37703829/165860451-a2b350af-9a6f-44ac-8bba-a8837d06a98e.jpg)

**Comment by DK-1989** [comment]
I get the same error and use Cura? why is this? do I need to uncomment the same? but I want to use the bed mesh...

**Comment by RobRobM** [comment]
sorry for the late reply. Do you still need help?

**Comment by Thormus** [comment]
> sorry for the late reply. Do you still need help? 

I ended up figuring it out from the klipper discord. But since then I have sold my s1 and have a Prusa now. Appreciate you offing help.

**Comment by RobRobM** [comment]
No problem. Happy printing.
