### ISSUE TITLE
start_print superslicer

### ISSUE THREAD

**Issue by emilianovilla** [RobRobM/e3s1-on-klipper#4]
Hello, could you share your gcode start of the super slicer to pass all the variables to the start_print?

**Comment by RobRobM** [comment]
This is what I use:
`START_PRINT BED_TEMP=[first_layer_bed_temperature]  EXTRUDER_TEMP=[first_layer_temperature] AREA_START={first_layer_print_min[0]},{first_layer_print_min[1]} AREA_END={first_layer_print_max[0]},{first_layer_print_max[1]}`
